title: Your awesome title is so awesome!
author: haltiamreptar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An awsesome thing for github-pages-with-jekyll

# social links

github_username: haltiamreptar

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
